title: Vlad
author: Vladislav Kostylev
email: kostylev.v@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My desc

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
